language: python

addons:
  postgresql: "9.6"

services:
  - postgresql

python:
  - "3.5"
  - "3.6"

cache: pip

env:
  global:
    - DATA_DIR=/tmp/matcher

install:
  - pip install codecov
  - pip install -r requirements-dev.txt
  - python setup.py develop

before_script:
  - psql -c 'create database matcher;' -U postgres

script:
  - matcher db upgrade
  - python setup.py flake8
  - pytest --cov=./

after_success:
  - codecov
