version: '3.4'
services:
  web:
    build: .
    image: sandhose/matcher:latest
    command: gunicorn -w 4 matcher:app -b 0.0.0.0:5000
    expose:
      - "5000"
    env_file:
      - docker-compose.env
    depends_on:
      - redis
      - db
      - migrate
    secrets:
      - postgres-password
      - secret-key
    volumes:
      - data:/data
    networks:
      - internal
      - proxy
    labels:
      - traefik.frontend.rule=Host:matcher.test
      - traefik.docker.network=proxy

  worker:
    build: .
    image: sandhose/matcher:latest
    command: matcher worker -l info --uid nobody --gid nobody
    env_file:
      - docker-compose.env
    depends_on:
      - redis
      - db
      - migrate
    volumes:
      - data:/data
    secrets:
      - postgres-password
      - secret-key
    networks:
      - internal
    labels:
      - traefik.enable=false

  migrate:
    build: .
    image: sandhose/matcher:latest
    command: matcher db upgrade
    env_file:
      - docker-compose.env
    depends_on:
      - redis
      - db
    secrets:
      - postgres-password
      - secret-key
    networks:
      - internal
    labels:
      - traefik.enable=false

  redis:
    image: redis:alpine
    volumes:
      - 'redis:/data'
    networks:
      - internal
    labels:
      - traefik.enable=false

  flower:
    image: mher/flower:latest
    environment:
      CELERY_BROKER_URL: redis://redis:6379/
    depends_on:
      - redis
      - worker
    networks:
      - internal
      - proxy
    labels:
      - traefik.frontend.rule=Host:matcher.test;PathPrefixStrip:/flower/
      - traefik.docker.network=proxy

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: matcher
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    secrets:
      - postgres-password
    networks:
      - internal
    labels:
      - traefik.enable=false

  scrapyd:
    build: ./scrapyd
    image: sandhose/obs-scrapyd:latest
    volumes:
      - scrapy:/var/lib/scrapyd
    networks:
      - internal
      - proxy
    labels:
      - traefik.frontend.rule=Host:scrapyd.test
      - traefik.docker.network=proxy

volumes:
  redis:
  postgres:
  scrapy:
  data:

secrets:
  postgres-password:
    file: ./secrets/postgres-password
  secret-key:
    file: ./secrets/secret-key
