version: '3.4'

# This exposes everything through træfik and allows hot-reloading of the app

x-internal:
  &internal
  networks:
    - internal
  labels:
    traefik.enable: false

services:
  web:
    command: >
      sh -c '
      matcher download-countries && 
      gunicorn -w 4 matcher:app -b 0.0.0.0:5000 --reload
      '
    volumes:
      - './matcher:/app/matcher'
    networks:
      - internal
      - proxy
    labels:
      traefik.frontend.rule: Host:matcher.test
      traefik.docker.network: proxy

  flower:
    image: mher/flower:latest
    networks:
      - internal
      - proxy
    labels:
      traefik.frontend.rule: Host:flower.test
      traefik.docker.network: proxy


  scrapyd:
    networks:
      - internal
      - proxy
    labels:
      traefik.frontend.rule: Host:scrapyd.test
      traefik.docker.network: proxy

  worker:
    command: >
      sh -c '
      pip install watchdog &&
      watchmedo auto-restart -D -R -p "**/*.py" -- matcher worker -l info -E --uid nobody --gid nobody
      '
    volumes:
      - './matcher:/app/matcher'
    << : *internal

  redis: *internal
  db:
    << : *internal
    ports:
      - "5432:5432"

networks:
  internal:
    external: false
  proxy:
    external: true
