version: "3.4"
services:
  web:
    build: .
    image: sandhose/matcher:latest
    command: gunicorn -k gevent -w 4 matcher:app -b 0.0.0.0:5000
    expose:
      - "5000"
    env_file:
      - docker-compose.env
    depends_on:
      - redis
      - db
      - migrate
    secrets:
      - postgres-password
      - secret-key
    volumes:
      - data:/data
    networks:
      - internal
      - proxy
    labels:
      - traefik.frontend.rule=Host:matcher.test
      - traefik.docker.network=proxy
      - traefik.enable=true

  worker:
    build: .
    image: sandhose/matcher:latest
    command: celery worker -A matcher:celery -P gevent -l info --uid nobody --gid nobody
    env_file:
      - docker-compose.env
    depends_on:
      - redis
      - db
      - migrate
    volumes:
      - data:/data
    secrets:
      - postgres-password
      - secret-key
    networks:
      - internal

  migrate:
    build: .
    image: sandhose/matcher:latest
    command: matcher db upgrade
    env_file:
      - docker-compose.env
    depends_on:
      - redis
      - db
    secrets:
      - postgres-password
      - secret-key
    networks:
      - internal

  redis:
    image: redis:alpine
    volumes:
      - "redis:/data"
    networks:
      - internal

  flower:
    image: mher/flower:latest
    environment:
      CELERY_BROKER_URL: redis://redis:6379/
    depends_on:
      - redis
      - worker
    networks:
      - internal
      - proxy
    labels:
      - traefik.frontend.rule=Host:matcher.test;PathPrefixStrip:/flower/
      - traefik.docker.network=proxy
      - traefik.enable=true

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: matcher
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    volumes:
      - "postgres:/var/lib/postgresql/data"
    secrets:
      - postgres-password
    networks:
      - internal

volumes:
  redis:
  postgres:
  data:

secrets:
  postgres-password:
    file: ./secrets/postgres-password
  secret-key:
    file: ./secrets/secret-key
